"""Add registered_date to donors

Revision ID: c0ab443ac045
Revises: 6f05c0257657
Create Date: 2026-06-30 15:10:42.433069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ab443ac045'
down_revision: Union[str, Sequence[str], None] = '6f05c0257657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('registered_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donors', 'registered_date')
    # ### end Alembic commands ###
